package lk.ijse.bookshop.util;

public enum Routes {
    LOGIN,PASSWORDRESET,TRUERESET,CREATEACCOUNT,DASHBOARD,ADMINWINDOW,EMPLOYEE,SUPPLIERORDER,SUPPLIERDETAILS,OFFERS,PAYMENT,EXPENDITURE,
    CASHIERWINDOW,CASHIERCUSTOMER,CASHIERPLACEORDER

}
